### ISSUE TITLE
Do not modify code automatically. 

### ISSUE THREAD

**Issue by WolfgangFahl** [Kenny2github/Piwo#7]
Currently users are forced to use the extra functionality provided by mw.py
```python
from sys import argv
from os import environ as env
from cgi import escape as hsc

MW_ROOT = env.get('MW_ROOT', None)
GRAM_NAME = env.get('MW_GRAM_NAME', None)
argv[0] = '#piwo:' + GRAM_NAME
```
which might lead e.g. to:
```
Traceback (most recent call last):
  File "/tmp/BITPlanDB2Wiki.py", line 3, in <module>
    import mw
  File "/var/www/mediawiki/mediawiki-1.35.0/extensions/Piwo/mw.py", line 3, in <module>
    from cgi import escape as hsc
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)
```
This dependency is not explained in the description of the extension yet and leads to extra effort in using it.

It also breaks debugging and is unnecessary. If need be users can do the import themselves. At least this "feature" should be optional and there should be a way to switch it off without modifying the code.

**Comment by WolfgangFahl** [comment]
My current workaround is
```php
	$keepCodeAsIs=(strpos($content, "from mw import") || strpos($content, "import mw")) ;
	$keepCodeAsIs=true;
	if ($keepCodeAsIs) {
```

**Comment by Kenny2github** [comment]
Apparently some version of Python 3 removed `cgi.escape` - the function is now `html.escape` instead. If that is the only issue with the module, all that needs to be changed is `from cgi import escape as hsc` → `from html import escape as hsc`.
